name: SonarScan-Build

on: 
 workflow_dispatch:

jobs:
  SonarScan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
         fetch-depth: 0
         
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
            SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        with:
          args: >
              -Dsonar.organization=pramodvsnaik
              -Dsonar.projectKey=aks-gitops
              -Dsonar.host.url=https://sonarcloud.io


      - name: Az Login
        uses: Azure/login@v2.3.0
        with:
          client-id:
          subscription-id:
          tenant-id:
          creds:

      - name: Azure CLI Action
        uses: Azure/cli@v2.2.0
        with:
          # Specify the script here
          inlineScript: |
            
            
          
 
   
